### ISSUE TITLE
pip install question

### ISSUE THREAD

**Issue by rttomlinson** [ryanhiebert/django-session-header#2]
Hi, I had two questions. Is this package available in PyPi? And if not, how would you recommend I install it? I'm getting a no matching distribution error when trying to `pip install`.
My other question was about comparing this method versus passing a JWT. It seems that a lot of sites opt for the JWT but using the Django sessions is nice because it's already been implemented. If going the JWT route, would I need to reroll everything with session management? (though I'm sure there are plenty of libraries that plug-in JWTs with django) Just wanted some insight into that. Thanks!

**Comment by ryanhiebert** [comment]
I don't currently have this package on PyPI, but you can install using `pip install git+https://github.com/ryanhiebert/django-session-header@master`. I'm not personally using it, and for the project I had in mind for it I've ended up using JWTs, but that's mostly because I have to use them for other reasons anyway, not because I know of any particular issues with this approach.

I see this approach as having some nice features, in particular being that the sessions are server-side, so they can be immediately invalidated by simply removing the session. JWTs have to have an expiration date, and so they fill a different purpose than a session does. I don't know of any libraries that integrate JWTs and Django sessions, so I can't give you any particular guidance on that.

This is not something I'm using it production, so take that for what it's worth, but if you try it out and think I'm onto something here, I'll be happy to release it to PyPI. And if you find some improvements that need to be made and want to write some pull requests, I'll be happy to review them and make you a maintainer after a good pull request or two!

**Comment by rttomlinson** [comment]
Awesome and thanks so much. I have a feeling that I might be switching over to JWTs at some point too but this would be nice to get me going. I'll let you know how this approach fares in a production environment.

**Comment by ryanhiebert** [comment]
Neat. I'm kinda psyched to see how it works! Thanks!
